
create database fitnessTracker;
use fitnessTracker;
create table overweight_female_workout(id int primary key auto_increment,day int not null,exercise_name varchar(255) not null,exercise_description text not null,amount int not null,exercise_url text not null);



insert into overweight_female_workout(day,exercise_name,exercise_description,amount,exercise_url) 
values(1,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true'),
	(1,'ALTERNATE SIDE DONKEY KICKS','Take the support of your hands and knees.Keep the knees 90 degrees angle.Slowly raise your left leg behind you until your left thigh comes parallel to the floor.Make the foot towards ceiling by stretching your glutes. Then return to the starting position and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/dokey_kicks_right.jpeg?raw=true'),
    (1,'ALTERNATE SIDE BALANCE PLANKS','Initially stand on one leg.Bend up to 90 degrees angle. Stretch both the arms forward and the other leg backward.Try to keep the hands and legs straight.Then come to the initial position.',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
    (1,'ALTERNATE LUNGES WITH LEGS','Start by standing,with your feet few inches apart.Keep your hands on the hip.Sit on the right kneeby bending it backside and bend left knee forward.Come back to the initial position and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
    
(2,'INVERTED BOARD','Sit on the floor with legs extended in front of you,Place your hands behind you.Press into your palms,lift your hips and torso towards the ceiling.Stay in this position for long as possible',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/inverted_board.jpeg?raw=true'),
(2,'ALTERNATE LEG GLUTE BRIDGE','Initially lie on the floor.Lift the hips by pushing through the floor with your heels and knees bent at 90 degrees.A Straight line should form from shoulders to knees.Extend the leg keeping to the straight line.Lower your hips and repeat',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/glute_bridge.jpeg?raw=true'),
(2,'PLANK JACK','Begin in the plank position with your shoulders over your wist,your body in one straight line and your feet together.in first ju mp outstretch your leg and in second jump join your legs.Jump as qickly as possible,but keep your pelvis steady and dont let your booty rise towards the ceilings',15,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_jack.jpeg?raw=true'),
(2,'JUMP SQUAT','Stand with your feet shoulder-width apart.Start by doing a regular squat,then jump up explosively.When u lend come to the squat position to complete one rep,lend as quietly as possible and repeat it ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/jump_squat.jpeg?raw=true'),
(2,'ALTERNATE PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your one lag for few seconds as it is possible,Now,lower your this leg and raise your other leg,Now come back to intial position,Repeat this',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
      
(3,'ALTERNATER FORWARD LUNGE WITH TWIST','Stand with your feet wide apart.Take your one leg forward, bend until it reaches 90 degrees and other leg parallel to the ground.Hands behind the neck.Rotate your torso to the left.untwist and stand back up ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(3,'GLUTE BRIDGE','Lie on your back,arms down by your sides.Bend your knees plant your feet flat on the floor.Lift your hips towards the ceiling.Hold in this position for few seconds and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/glute_bridge.jpeg?raw=true '),
(3,'BURPEES','Start from standing position.Come down in a squat position with your hands on the ground in front of you.Jump your feet back to plank position.Again come back to the earlier squat position Repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/burpees.jpeg?raw=true '),
(3,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(3,'SWIMMING','Lie down with your face downwards,by stretching your hands forward.Raise your opposite arm and leg alternatively',35,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/swimming.jpeg?raw=true '),

(4,'REST','Rest today',0,'REST'),

(5,'COILED BURST WITH OUTSTRETCHED ARMS ','Intially lie down on your back and bend your legs,Take the support of your hands on the side,lift your head and touch your heels alternatively with your hands',20, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/coiled_burst_with_outstretched_arms.jpeg?raw=true'),
(5,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(5,'LUNGES WITH ALTERNATE LEGS','Start by standing,with your feets few inches apart,keep your hands on the hip,Stretch your right leg and bring your body down,till your right thigh is parallel to floor,come back to the intial position and repeat the same on the left leg',30,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(5,'MOUNTAIN CLIMBER FEET JOINED BESIDE','Assume a pushup position with your arms straight and your body in a straight line from your head to your ankles.Bring both feet back to your hands by bending your legs.return to the initial position and repeat it',25,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/mountain_climber.jpeg?raw=true'),
(5,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',35, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),

(6,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',35,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
(6,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(6,'BULGARIAN SQUAT WITH LEFT LEG','Begin by placing your left leg on a bench,box,stair or chair behind you, with your left leg straight.Bend your left leg towards the ground and right leg to 90 degrees .Return to the initial position and repeat it',22,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/bulgarian_squat_with_left_leg.jpeg?raw=true'),
(6,'MOUNTAIN CLIMBER FEET JOINED BESIDE','Assume a pushup position with your arms straight and your body in a straight line from your head to your ankles.Bring both feet back to your hands by bending your legs.return to the initial position and repeat it',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/mountain_climber.jpeg?raw=true'),
(6,'SWIMMING','Lie down with your face downwards,by stretching your hands forward.Raise your opposite arm and leg alternatively',35, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/swimming.jpeg?raw=true '),


(7,'JACKIE KNIFE FROM FLAT','Lie on the floor,hands extended behind your hand,legs straight.Exhale bending at the waist,lift your arms and legs at 35-45 degrees dfrom the ground and the arms should be parallel to the legs inhale come back to the initial position and repeat',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/jack_knife_from%20flat.jpeg?raw=true'),
(7,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',21,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(7,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',40,'https://raw.githubusercontent.com/saket2408/fitnessTracker-project/master/images/male/plank.jpeg'),
(7,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(7,'LUNGES WITH ALTERNATE LEGS','Start by standing,with your feets few inches apart,keep your hands on the hip,Stretch your right leg and bring your body down,till your right thigh is parallel to floor,come back to the intial position and repeat the same on the left leg',30, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(8,'REST','REST',0,'REST'),

(9,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',20, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(9,'ALTERNATE SIDE DONKEY KICKS','Take the support of your hands and knees.Keep the knees 90 degrees angle.Slowly raise your left leg behind you until your left thigh comes parallel to the floor.Make the foot towards ceiling by stretching your glutes. Then return to the starting position and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/dokey_kicks_right.jpeg?raw=true'),
    (9,'ALTERNATE SIDE BALANCE PLANKS','Initially stand on one leg.Bend up to 90 degrees angle. Stretch both the arms forward and the other leg backward.Try to keep the hands and legs straight.Then come to the initial position.',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
    (9,'ALTERNATE LUNGES WITH LEGS','Start by standing,with your feet few inches apart.Keep your hands on the hip.Sit on the right kneeby bending it backside and bend left knee forward.Come back to the initial position and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
    
(9,'INVERTED BOARD','Sit on the floor with legs extended in front of you,Place your hands behind you.Press into your palms,lift your hips and torso towards the ceiling.Stay in this position for long as possible',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/inverted_board.jpeg?raw=true'),
(10,'ALTERNATE LEG GLUTE BRIDGE','Initially lie on the floor.Lift the hips by pushing through the floor with your heels and knees bent at 90 degrees.A Straight line should form from shoulders to knees.Extend the leg keeping to the straight line.Lower your hips and repeat',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/glute_bridge.jpeg?raw=true'),
(10,'PLANK JACK','Begin in the plank position with your shoulders over your wist,your body in one straight line and your feet together.in first ju mp outstretch your leg and in second jump join your legs.Jump as qickly as possible,but keep your pelvis steady and dont let your booty rise towards the ceilings',15,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_jack.jpeg?raw=true'),
(10,'JUMP SQUAT','Stand with your feet shoulder-width apart.Start by doing a regular squat,then jump up explosively.When u lend come to the squat position to complete one rep,lend as quietly as possible and repeat it ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/jump_squat.jpeg?raw=true'),
(10,'ALTERNATE PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your one lag for few seconds as it is possible,Now,lower your this leg and raise your other leg,Now come back to intial position,Repeat this',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
      
(10,'ALTERNATER FORWARD LUNGE WITH TWIST','Stand with your feet wide apart.Take your one leg forward, bend until it reaches 90 degrees and other leg parallel to the ground.Hands behind the neck.Rotate your torso to the left.untwist and stand back up ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(11,'GLUTE BRIDGE','Lie on your back,arms down by your sides.Bend your knees plant your feet flat on the floor.Lift your hips towards the ceiling.Hold in this position for few seconds and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/glute_bridge.jpeg?raw=true '),
(11,'BURPEES','Start from standing position.Come down in a squat position with your hands on the ground in front of you.Jump your feet back to plank position.Again come back to the earlier squat position Repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/burpees.jpeg?raw=true '),
(11,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(11,'SWIMMING','Lie down with your face downwards,by stretching your hands forward.Raise your opposite arm and leg alternatively',35,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/swimming.jpeg?raw=true '),
(11,'ALTERNATER FORWARD LUNGE WITH TWIST','Stand with your feet wide apart.Take your one leg forward, bend until it reaches 90 degrees and other leg parallel to the ground.Hands behind the neck.Rotate your torso to the left.untwist and stand back up ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),


(12,'REST','Rest today',0,'REST'),

(13,'COILED BURST WITH OUTSTRETCHED ARMS ','Intially lie down on your back and bend your legs,Take the support of your hands on the side,lift your head and touch your heels alternatively with your hands',20, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/coiled_burst_with_outstretched_arms.jpeg?raw=true'),
(13,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(13,'LUNGES WITH ALTERNATE LEGS','Start by standing,with your feets few inches apart,keep your hands on the hip,Stretch your right leg and bring your body down,till your right thigh is parallel to floor,come back to the intial position and repeat the same on the left leg',30,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(13,'MOUNTAIN CLIMBER FEET JOINED BESIDE','Assume a pushup position with your arms straight and your body in a straight line from your head to your ankles.Bring both feet back to your hands by bending your legs.return to the initial position and repeat it',25,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/mountain_climber.jpeg?raw=true'),
(13,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',35, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),

(14,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',35,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
(14,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(14,'BULGARIAN SQUAT WITH LEFT LEG','Begin by placing your left leg on a bench,box,stair or chair behind you, with your left leg straight.Bend your left leg towards the ground and right leg to 90 degrees .Return to the initial position and repeat it',22,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/bulgarian_squat_with_left_leg.jpeg?raw=true'),
(14,'MOUNTAIN CLIMBER FEET JOINED BESIDE','Assume a pushup position with your arms straight and your body in a straight line from your head to your ankles.Bring both feet back to your hands by bending your legs.return to the initial position and repeat it',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/mountain_climber.jpeg?raw=true'),
(14,'SWIMMING','Lie down with your face downwards,by stretching your hands forward.Raise your opposite arm and leg alternatively',35, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/swimming.jpeg?raw=true '),


(15,'JACKIE KNIFE FROM FLAT','Lie on the floor,hands extended behind your hand,legs straight.Exhale bending at the waist,lift your arms and legs at 35-45 degrees dfrom the ground and the arms should be parallel to the legs inhale come back to the initial position and repeat',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/jack_knife_from%20flat.jpeg?raw=true'),
(15,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',21,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(15,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',40,'https://raw.githubusercontent.com/saket2408/fitnessTracker-project/master/images/male/plank.jpeg'),
(15,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(15,'LUNGES WITH ALTERNATE LEGS','Start by standing,with your feets few inches apart,keep your hands on the hip,Stretch your right leg and bring your body down,till your right thigh is parallel to floor,come back to the intial position and repeat the same on the left leg',30, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(16,'REST','REST',0,'REST'),

(17,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',20, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(17,'ALTERNATE SIDE DONKEY KICKS','Take the support of your hands and knees.Keep the knees 90 degrees angle.Slowly raise your left leg behind you until your left thigh comes parallel to the floor.Make the foot towards ceiling by stretching your glutes. Then return to the starting position and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/dokey_kicks_right.jpeg?raw=true'),
    (17,'ALTERNATE SIDE BALANCE PLANKS','Initially stand on one leg.Bend up to 90 degrees angle. Stretch both the arms forward and the other leg backward.Try to keep the hands and legs straight.Then come to the initial position.',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
    (17,'ALTERNATE LUNGES WITH LEGS','Start by standing,with your feet few inches apart.Keep your hands on the hip.Sit on the right kneeby bending it backside and bend left knee forward.Come back to the initial position and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
    
(17,'INVERTED BOARD','Sit on the floor with legs extended in front of you,Place your hands behind you.Press into your palms,lift your hips and torso towards the ceiling.Stay in this position for long as possible',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/inverted_board.jpeg?raw=true'),
(18,'ALTERNATE LEG GLUTE BRIDGE','Initially lie on the floor.Lift the hips by pushing through the floor with your heels and knees bent at 90 degrees.A Straight line should form from shoulders to knees.Extend the leg keeping to the straight line.Lower your hips and repeat',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/glute_bridge.jpeg?raw=true'),
(18,'PLANK JACK','Begin in the plank position with your shoulders over your wist,your body in one straight line and your feet together.in first ju mp outstretch your leg and in second jump join your legs.Jump as qickly as possible,but keep your pelvis steady and dont let your booty rise towards the ceilings',15,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_jack.jpeg?raw=true'),
(18,'JUMP SQUAT','Stand with your feet shoulder-width apart.Start by doing a regular squat,then jump up explosively.When u lend come to the squat position to complete one rep,lend as quietly as possible and repeat it ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/jump_squat.jpeg?raw=true'),
(18,'ALTERNATE PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your one lag for few seconds as it is possible,Now,lower your this leg and raise your other leg,Now come back to intial position,Repeat this',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
      
(18,'ALTERNATER FORWARD LUNGE WITH TWIST','Stand with your feet wide apart.Take your one leg forward, bend until it reaches 90 degrees and other leg parallel to the ground.Hands behind the neck.Rotate your torso to the left.untwist and stand back up ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(19,'GLUTE BRIDGE','Lie on your back,arms down by your sides.Bend your knees plant your feet flat on the floor.Lift your hips towards the ceiling.Hold in this position for few seconds and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/glute_bridge.jpeg?raw=true '),
(19,'BURPEES','Start from standing position.Come down in a squat position with your hands on the ground in front of you.Jump your feet back to plank position.Again come back to the earlier squat position Repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/burpees.jpeg?raw=true '),
(19,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(19,'SWIMMING','Lie down with your face downwards,by stretching your hands forward.Raise your opposite arm and leg alternatively',35,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/swimming.jpeg?raw=true '),
(19,'COILED BURST WITH OUTSTRETCHED ARMS ','Intially lie down on your back and bend your legs,Take the support of your hands on the side,lift your head and touch your heels alternatively with your hands',20, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/coiled_burst_with_outstretched_arms.jpeg?raw=true'),

(20,'REST','Rest today',0,'REST'),

(21,'COILED BURST WITH OUTSTRETCHED ARMS ','Intially lie down on your back and bend your legs,Take the support of your hands on the side,lift your head and touch your heels alternatively with your hands',20, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/coiled_burst_with_outstretched_arms.jpeg?raw=true'),
(21,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(21,'LUNGES WITH ALTERNATE LEGS','Start by standing,with your feets few inches apart,keep your hands on the hip,Stretch your right leg and bring your body down,till your right thigh is parallel to floor,come back to the intial position and repeat the same on the left leg',30,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(21,'MOUNTAIN CLIMBER FEET JOINED BESIDE','Assume a pushup position with your arms straight and your body in a straight line from your head to your ankles.Bring both feet back to your hands by bending your legs.return to the initial position and repeat it',25,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/mountain_climber.jpeg?raw=true'),
(21,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',35, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),

(22,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',35,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
(22,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(22,'BULGARIAN SQUAT WITH LEFT LEG','Begin by placing your left leg on a bench,box,stair or chair behind you, with your left leg straight.Bend your left leg towards the ground and right leg to 90 degrees .Return to the initial position and repeat it',22,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/bulgarian_squat_with_left_leg.jpeg?raw=true'),
(22,'MOUNTAIN CLIMBER FEET JOINED BESIDE','Assume a pushup position with your arms straight and your body in a straight line from your head to your ankles.Bring both feet back to your hands by bending your legs.return to the initial position and repeat it',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/mountain_climber.jpeg?raw=true'),
(22,'SWIMMING','Lie down with your face downwards,by stretching your hands forward.Raise your opposite arm and leg alternatively',35, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/swimming.jpeg?raw=true '),


(23,'JACKIE KNIFE FROM FLAT','Lie on the floor,hands extended behind your hand,legs straight.Exhale bending at the waist,lift your arms and legs at 35-45 degrees dfrom the ground and the arms should be parallel to the legs inhale come back to the initial position and repeat',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/jack_knife_from%20flat.jpeg?raw=true'),
(23,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',21,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(23,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',40,'https://raw.githubusercontent.com/saket2408/fitnessTracker-project/master/images/male/plank.jpeg'),
(23,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(23,'LUNGES WITH ALTERNATE LEGS','Start by standing,with your feets few inches apart,keep your hands on the hip,Stretch your right leg and bring your body down,till your right thigh is parallel to floor,come back to the intial position and repeat the same on the left leg',30, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(24,'REST','REST',0,'REST'),
(25,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',20, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(25,'ALTERNATE SIDE DONKEY KICKS','Take the support of your hands and knees.Keep the knees 90 degrees angle.Slowly raise your left leg behind you until your left thigh comes parallel to the floor.Make the foot towards ceiling by stretching your glutes. Then return to the starting position and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/dokey_kicks_right.jpeg?raw=true'),
    (25,'ALTERNATE SIDE BALANCE PLANKS','Initially stand on one leg.Bend up to 90 degrees angle. Stretch both the arms forward and the other leg backward.Try to keep the hands and legs straight.Then come to the initial position.',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
    (25,'ALTERNATE LUNGES WITH LEGS','Start by standing,with your feet few inches apart.Keep your hands on the hip.Sit on the right kneeby bending it backside and bend left knee forward.Come back to the initial position and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
    
(25,'INVERTED BOARD','Sit on the floor with legs extended in front of you,Place your hands behind you.Press into your palms,lift your hips and torso towards the ceiling.Stay in this position for long as possible',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/inverted_board.jpeg?raw=true'),
(26,'ALTERNATE LEG GLUTE BRIDGE','Initially lie on the floor.Lift the hips by pushing through the floor with your heels and knees bent at 90 degrees.A Straight line should form from shoulders to knees.Extend the leg keeping to the straight line.Lower your hips and repeat',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/glute_bridge.jpeg?raw=true'),
(26,'PLANK JACK','Begin in the plank position with your shoulders over your wist,your body in one straight line and your feet together.in first ju mp outstretch your leg and in second jump join your legs.Jump as qickly as possible,but keep your pelvis steady and dont let your booty rise towards the ceilings',15,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_jack.jpeg?raw=true'),
(26,'JUMP SQUAT','Stand with your feet shoulder-width apart.Start by doing a regular squat,then jump up explosively.When u lend come to the squat position to complete one rep,lend as quietly as possible and repeat it ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/jump_squat.jpeg?raw=true'),
(26,'ALTERNATE PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your one lag for few seconds as it is possible,Now,lower your this leg and raise your other leg,Now come back to intial position,Repeat this',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
      
(26,'ALTERNATER FORWARD LUNGE WITH TWIST','Stand with your feet wide apart.Take your one leg forward, bend until it reaches 90 degrees and other leg parallel to the ground.Hands behind the neck.Rotate your torso to the left.untwist and stand back up ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(27,'GLUTE BRIDGE','Lie on your back,arms down by your sides.Bend your knees plant your feet flat on the floor.Lift your hips towards the ceiling.Hold in this position for few seconds and repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/glute_bridge.jpeg?raw=true '),
(27,'BURPEES','Start from standing position.Come down in a squat position with your hands on the ground in front of you.Jump your feet back to plank position.Again come back to the earlier squat position Repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/burpees.jpeg?raw=true '),
(27,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(27,'SWIMMING','Lie down with your face downwards,by stretching your hands forward.Raise your opposite arm and leg alternatively',35,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/swimming.jpeg?raw=true '),
(27,'ALTERNATER FORWARD LUNGE WITH TWIST','Stand with your feet wide apart.Take your one leg forward, bend until it reaches 90 degrees and other leg parallel to the ground.Hands behind the neck.Rotate your torso to the left.untwist and stand back up ',20,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),


(28,'REST','Rest today',0,'REST'),

(29,'COILED BURST WITH OUTSTRETCHED ARMS ','Intially lie down on your back and bend your legs,Take the support of your hands on the side,lift your head and touch your heels alternatively with your hands',20, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/coiled_burst_with_outstretched_arms.jpeg?raw=true'),
(29,'PUSHUPS','Intially face-down prone position on the floor,Stretch your arms and touch the floor,Raise yourself by pushing the ground away from you,Repeat this',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/push_ups.jpeg?raw=true '),
(29,'LUNGES WITH ALTERNATE LEGS','Start by standing,with your feets few inches apart,keep your hands on the hip,Stretch your right leg and bring your body down,till your right thigh is parallel to floor,come back to the intial position and repeat the same on the left leg',30,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/lunge_with_left_leg%20.jpeg?raw=true'),
(29,'MOUNTAIN CLIMBER FEET JOINED BESIDE','Assume a pushup position with your arms straight and your body in a straight line from your head to your ankles.Bring both feet back to your hands by bending your legs.return to the initial position and repeat it',25,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/mountain_climber.jpeg?raw=true'),
(29,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',35, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),

(30,'PLANK WITH LEG LIFT','Be on your toes and forearms with your body straight,Raise your left lag for few seconds as it is possible,Now,lower your left leg and raise your right leg,Now come back to intial position,Repeat this',35,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/plank_in_balance_left_side.jpeg?raw=true'),
(30,'FLUTTER KICKS','Stand by lying on your back,Keep your arms on the side and lift your legs,let the legs be as straight as possible,now quickly raise your right leg and at the same time,lower your left leg,then do the same on the other leg repeat it',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/flutter_kicks.jpeg?raw=true '),
(30,'BULGARIAN SQUAT WITH LEFT LEG','Begin by placing your left leg on a bench,box,stair or chair behind you, with your left leg straight.Bend your left leg towards the ground and right leg to 90 degrees .Return to the initial position and repeat it',22,'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/bulgarian_squat_with_left_leg.jpeg?raw=true'),
(30,'MOUNTAIN CLIMBER FEET JOINED BESIDE','Assume a pushup position with your arms straight and your body in a straight line from your head to your ankles.Bring both feet back to your hands by bending your legs.return to the initial position and repeat it',25, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/mountain_climber.jpeg?raw=true'),
(30,'SWIMMING','Lie down with your face downwards,by stretching your hands forward.Raise your opposite arm and leg alternatively',35, 'https://github.com/saket2408/fitnessTracker-project/blob/master/images/underweight-female/swimming.jpeg?raw=true ');






