spring:
  application:
    name: feign-client-service      
      
server:
  port: 8010

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

       
      
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management: 
  endpoints: 
    web: 
      exposure: 
        include: 'hystrix.stream'
      