spring:
  application:
    name: underweight-female-exercise-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/fitnessTracker
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
      
server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      

