spring:
  application:
    name: userdetails-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/fitnessTracker
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
      
server:
  port: 8008
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
